name: p
description: "Toma las medidas, con la estación meteorologica"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bounce: ^1.0.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/"
